-- Initial schema for sit-vnpay (H2 PostgreSQL mode + PostgreSQL)

CREATE TABLE IF NOT EXISTS partner_config (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(200)  NOT NULL,
    flow            VARCHAR(20)   NOT NULL,
    tmn_code        VARCHAR(20)   NOT NULL,
    secret_key      VARCHAR(500)  NOT NULL,
    return_url      VARCHAR(500)  NOT NULL DEFAULT '',
    ipn_url         VARCHAR(500)  NOT NULL,
    note            VARCHAR(500),
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP     NOT NULL
);

CREATE TABLE IF NOT EXISTS sit_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR(200)  NOT NULL,
    email           VARCHAR(200)  NOT NULL,
    password_hash   VARCHAR(100)  NOT NULL,
    role            VARCHAR(20)   NOT NULL,
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP     NOT NULL,
    CONSTRAINT uk_sit_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS test_session (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id          BIGINT        NOT NULL,
    partner_name        VARCHAR(200),
    tmn_code            VARCHAR(20),
    note                VARCHAR(500),
    status              VARCHAR(20)   NOT NULL DEFAULT 'OPEN',
    created_by_email    VARCHAR(200),
    created_at          TIMESTAMP     NOT NULL,
    updated_at          TIMESTAMP     NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_test_session_partner_id ON test_session (partner_id);
CREATE INDEX IF NOT EXISTS idx_test_session_created_by ON test_session (created_by_email);

CREATE TABLE IF NOT EXISTS test_run (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id          BIGINT,
    session_id          BIGINT,
    partner_name        VARCHAR(200),
    flow                VARCHAR(20)   NOT NULL,
    callback_type       VARCHAR(10)   NOT NULL,
    test_case           VARCHAR(30)   NOT NULL,
    txn_ref             VARCHAR(100),
    target_url          VARCHAR(1000),
    request_params      TEXT,
    http_status         INTEGER,
    response_body       TEXT,
    expected_rsp_code   VARCHAR(10),
    actual_rsp_code     VARCHAR(10),
    passed              BOOLEAN       NOT NULL DEFAULT FALSE,
    duration_ms         BIGINT,
    error_message       VARCHAR(1000),
    created_at          TIMESTAMP     NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_test_run_session_id ON test_run (session_id);
CREATE INDEX IF NOT EXISTS idx_test_run_partner_id ON test_run (partner_id);
CREATE INDEX IF NOT EXISTS idx_test_run_created_at ON test_run (created_at);

CREATE TABLE IF NOT EXISTS manual_acceptance (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id              BIGINT        NOT NULL,
    session_id              BIGINT,
    partner_name            VARCHAR(200),
    return_success_txn_ref  VARCHAR(100),
    return_success_image    TEXT,
    return_failed_txn_ref   VARCHAR(100),
    return_failed_image     TEXT,
    exception_handled       BOOLEAN,
    whitelist_ip_passed     BOOLEAN,
    log_storage_passed      BOOLEAN,
    note                    VARCHAR(1000),
    created_at              TIMESTAMP     NOT NULL,
    updated_at              TIMESTAMP     NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_manual_acceptance_session_id ON manual_acceptance (session_id);
CREATE INDEX IF NOT EXISTS idx_manual_acceptance_partner_id ON manual_acceptance (partner_id);
